nf_core_version: 3.1.1
repository_type: pipeline
template:
  author: "@scorreard"
  description: Workflow designed to generate variant catalogues, a list of variants
    and their frequencies in a population, from whole genome sequences.
  force: false
  is_nfcore: true
  name: variantcatalogue
  org: nf-core
  outdir: .
  version: 1.0dev
